baseURL: "https://sajadabdollahi.ir"
title: "Sajad Abdollahi"
paginate: 5
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45
defaultContentLanguage: "fa"
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Sajad Abdollahi"
  description: "Sajad's Personal Web Page"
  keywords: [Blog, Portfolio, Sajad, Abdollahi, "Sajad Abdollahi", "July Witch", JulyWitch]
  author: Sajad
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  assets:
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-icon-180x180.png"
    safari_pinned_tab: "icons/favicon.ico"
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/sajad-abdollahi-viracode/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/13547175/sajad-abdollahi"
    - name: github
      url: "https://github.com/JulyWitch"
    - name: telegram
      url: "https://t.me/julywitch"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

languages:
  fa:
    languageCode: "fa"
    languageName: "Farsi"
    languageDirection: rtl
    weight: 1
    params:
      languageAltTitle: "Farsi"
      homeInfoParams:
        Title: محمدسجاد عبداللهی
        Content: مهندس نرم‌افزار
    title: محمدسجاد عبداللهی
    menu:
      main:
        - name: "پست‌ها"
          url: posts
        - name: جستجو
          url: search
  en:
    languageName: "English"
    languageCode: "en"
    weight: 2
    params:
      homeInfoParams:
        Title: Sajad Abdollahi
        Content: Software Engineer
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
        - name: Search
          url: search

outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    category: categories
    tag: tags
    series: series

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
