baseURL: "https://julywitch.github.io/"
title: "Sajad Abdollahi"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Sajad Abdollahi"
  description: "Sajad's Personal Web Page"
  keywords: [Blog, Portfolio, Sajad, Abdollahi, "Sajad Abdollahi"]
  author: Sajad
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-icon-180x180.png"
    safari_pinned_tab: "icons/favicon.ico"
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/sajad-abdollahi-viracode/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/13547175/sajad-abdollahi"
    - name: github
      url: "https://github.com/JulyWitch"
    - name: telegram
      url: "https://t.me/julywitch"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/julywitch/julywitch.github.io/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

languages:
  en:
    languageName: "English"
    weight: 1
    params:
      enabled: true # needs to be explicitly set
      title: "Sajad Abdollahi"
      subtitle: "Flutter Developer"
      imageUrl: "/images/sajad.jpeg"
      imageWidth: 120
      imageHeight: 120
      imageTitle: "Sajad"
      buttons:
        - name: Posts
          url: posts
      label:
        text: "Home"
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 10

  fa:
    languageName: "fa"
    languagedirection: rtl
    weight: 2
    params:
      enabled: true # needs to be explicitly set
      languageAltTitle: "Farsi"
      title: "سجاد عبداللهی"
      subtitle: "توسعه دهنده فلاتر"
      imageUrl: "/images/sajad.jpeg"
      imageWidth: 120
      imageHeight: 120
      imageTitle: "Sajad"
      buttons:
        - name: پست ها
          url: posts
        # - name: Tags
        #   url: tags
      label:
        text: "خانه"
    title: سجاد عبداللهی
    menu:
      main:
        - name: "پست ها"
          url: posts
          weight: 1
outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    category: categories
    tag: tags
    series: series