baseURL: "https://sajadabdollahi.ir"
title: "Sajad Abdollahi"
paginate: 5
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Sajad Abdollahi"
  description: "Sajad's Personal Web Page"
  keywords: [Blog, Portfolio, Sajad, Abdollahi, "Sajad Abdollahi", "July Witch", JulyWitch]
  author: Sajad
  cover: 
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  assets:
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-icon-180x180.png"
    safari_pinned_tab: "icons/favicon.ico"
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/sajad-abdollahi-viracode/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/13547175/sajad-abdollahi"
    - name: github
      url: "https://github.com/JulyWitch"
    - name: telegram
      url: "https://t.me/julywitch"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

languages:
  en:
    languageName: "English"
    weight: 2
    params:
      enabled: true # needs to be explicitly set
      homeInfoParams:
        Title: Sajad Abdollahi
        Content: Software Engineer
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 10
        - name: Search
          url: search

  fa:
    languageName: "fa"
    languagedirection: rtl
    weight: 1
    params:
      enabled: true # needs to be explicitly set
      languageAltTitle: "Farsi"
      homeInfoParams:
        Title: سجاد عبداللهی
        Content: مهندس نرم‌افزار
    title: سجاد عبداللهی
    menu:
      main:
        - name: "پست ها"
          url: posts
          weight: 1
        - name: جستجو
          url: search
outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    category: categories
    tag: tags
    series: series

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
