baseURL: "https://julywitch.github.io/"
title: "Sajad Abdollahi"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Sajad Abdollahi"
  description: "Sajad's Personal Web Page"
  keywords: [Blog, Portfolio, Sajad, Abdollahi, "Sajad Abdollahi"]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-icon-180x180.png"
    safari_pinned_tab: "icons/favicon.ico"

  label:
    text: "Home"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Sajad Abdollahi"
    subtitle: "Flutter Developer"
    imageUrl: "/images/sajad.jpeg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Sajad"
    buttons:
      - name: Posts
        url: posts
      # - name: Tags
      #   url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/sajad-abdollahi-viracode/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/13547175/sajad-abdollahi"
    - name: github
      url: "https://github.com/JulyWitch"
    - name: telegram
      url: "https://t.me/julywitch"
      

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/julywitch/julywitch.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
